version: "3.4"

services:
  amadeus_flights:
    image: amadeus-flightst:v1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
